TerriaJS/nationalmap

server.js

It's a bit hacky, but it's better than the nasty "Cannot GET /foo" message that otherwise gets shown.
Addresses (but doesn't fix) https://github.com/TerriaJS/terriajs/issues/614

Redirect unknown URLs back to /. Better than "Cannot GET /..."

---

wwwroot/init/vic.json

The "vic at the top" bit won't work until TerriaJS/terriajs#715 is merged.

Make #vic put Victorian Government at the top, open it, and close NDS.

---

wwwroot/init/nm.json

After TerriaJS/terriajs#720, the previous initial extent doesn't look very good anymore.  This one looks better.

Specify a new initial extent.

---

.gitignore
CHANGES.md
gulpfile.js
index.js
package.json

The version is accessible by hovering the mouse over the NM logo in the top left corner of the screen.
The version number comes from the output of [git describe](http://git-scm.com/docs/git-describe) so for production releases it should just be one of our date version tags (e.g. `2015-05-28`).  For non-labelled builds, it shows the closest label (2015-05-28 in the screenshot below), the number of commits since that label (5), and the abbreviated hash of the head commit (g5604331).  If there are local modifications beyond what is checked into git, `(plus local modifications)` is added to the end.

Add a version number in the UI.

---

CHANGES.md
index.js
package.json

At Bill's request, given that ABS support will be adding a bunch of non-legend stuff to that tab in this release.  We can revisit afterward.

Rename Legend tab back to Now Viewing

---

wwwroot/index.html

It was hardcoded to `http`, which caused a warning in the browser console when accessing the app over `https`.

Download Roboto Mono font over https, too.

---

wwwroot/About.html
wwwroot/help/DataCatalogueTab.html
wwwroot/help/FrequentlyAskedQuestions.html
wwwroot/help/Help.html
wwwroot/help/HowTo.html
wwwroot/help/NowViewingTab.html
wwwroot/help/SearchTab.html
wwwroot/help/TableOfContents.html

The fonts on all the help pages are hardcoded to ```http```, this will not work over ```https```` connections.
Currently https://nationalmap.gov.au/ will not use the specified font (at least in Google Chrome).

Fix fonts not loading over https.

---

CHANGES.md
datasources/00_National_Data_Sets/00_01_Elevation.json
datasources/00_National_Data_Sets/00_06_Land.json

*  Renamed "Gravity Image" to "Gravity Anomaly" and update it to load from the new server (the old one is deprecated).
* Renamed "Magnetic Image" to "Magnetic Intensity" and update it to load from the new server (the old one is deprecated).
* Update the layer name used to access "SRTM 1 sec DEM Image".  The old one worked but was not advertised in the WMS server's GetCapabilities, which limited the quality of the metadata.

Dataset updates

---

CHANGES.md
server.js

This was motivated by adding CSW support.  Some CSW servers can only be queried by POSTing.

Add support for POST requests to proxy service

---

package.json
server.js
varnish/default.vcl
wwwroot/init/tind.json

* Change proxy in `server.js` to remove the `Expires` header entirely and to set the `max-age` in the `Cache-Control` header to the actual length of time to cache, as specified in the proxy URL (e.g. `/proxy/_1d/http://whatever` versus `/proxy/_50s/http://whatever`.
* Do not explicitly set the ttl for proxied requests the Varnish VCL file.  Varnish will set it automatically from by looking at the `Cache-Control` header.
* Cache for 14 days by default, instead of however many years.  Previously Varnish was doing this, but the headers (which are honored by web browsers and potentially other intermediate caches) were set incorrectly.
* Change `TIND.json` so that TIND tiles are cached for only 24 hours.

Add support for varying cache durations.

---

gulpfile.js

Just a minor improvement so that 'gulp watch' picks up changes in TerriaJS tests etc, to make testing a bit faster.

Include terriaJS outputs in 'gulp watch'

---

server.js

In the GA deployment of NationalMap, a reverse proxy (Apache I think) forwards requests to our varnish/node proxy and adds the `x-forwarded-host` header along the way.  Our node-based proxy then blindly includes this header in the request to the proxied URL.  Usually this is fine(-ish), but some servers look at this header in the same way they might look at the `host` header: as specifying which of a set of servers hosted at the same IP address is meant to respond to the request.  If the host is not among the hostnames the server thinks it should be serving for, it will fail (e.g. with a 404).
Our node proxy explicitly filters out the `host` header from incoming requests.  It should do the same with the `x-forwarded-host` header in order to fix the problem described above, which is what …

Remove x-forwarded-host from proxied requests.

---

package.json

Fixes TerriaJS/terriajs#1121. Related to TerriaJS/terriajs#1151.
Note: npm Leaflet 0.7.3 has incorrect L.version (0.7.2), but the installed package is actually 0.7.3 (see Leaflet/Leaflet#2735)

Downgrade Leaflet to 0.7.3

---

CHANGES.md
datasources/00_National_Data_Sets/00_00_Communications.json

To allow the server-provided descriptions to be used instead.
Fixes #153

Remove hardcoded descriptions from the Mobile Black Spot datasets

---

package.json
run_server.sh
stop_server.sh

Unfortunately npm doesn't launch scripts in bash on Windows, even if npm itself was invoked from bash (ugh).  So we have to do it explicitly.  We're already doing the same thing in package.json in TerriaJS, for what it's worth.
`npm start` still doesn't quite work, though, because `nohup` doesn't exist.

Explicitly use bash so that npm start works on Windows.

---

gulpfile.js

My CPU was running at a constant 17-18% with `gulp watch`. This reduces that to about 3.5%.

Increase all Gulp watch intervals to 1000ms to reduce OSX melting.

---

.dockerignore
Dockerfile

In the dockerfile itself I switch to 5.11 nodejs and added the gulp step.  I also changed the CMD to what is underlying the `npm start` so that it doesn't exit (Docker doesn't like background processes).

Removing some ignored files from Docker to get it to build

---

CHANGES.md
lib/Styles/NationalMap.less
lib/Views/PreviewLink.html
package.json

* Update CHANGES.md.
* Use TerriaJS 3.3.0.
* Don't show the one pixel border of the link to the preview of the new UI when the message is hidden.
* Keep the preview link above the 2D map.
I previously put these in #267; this separate pull request is a better idea.

Tweaks before release

---

package.json

Add `urijs` to package.json, since it is required by NationalMap's `lib/ViewModels/PreviewLinkViewModel.js`.

Add urijs to package.json

---

package.json

See also TerriaJS/terriajs#1771.

Use a new version of style-loader to work around Chrome sourcemaps bug.

---

wwwroot/config.json

So that the icon alone can be shown on a mobile device with a narrow screen.

Remove beta, separate Australia icon from NationalMap text.

---

wwwroot/data/regionMapping.json

This makes the `aus` region consistent with `sa4`, `lga` etc which all have a `_code` alias.
Makes the SDMX-JSON catalog item more streamlined.

Add aus_code to aliases for aus regiontype

---

wwwroot/init/test.json

Two more manual WPS tests added. At time of writing, region relies on an open pull request, and geojson relies on a branch not yet pushed, but I see no reason not to add them now.

Add region and geojson WPS tests

---

CHANGES.md
wwwroot/data/regionMapping.json

This makes region mapping work again when connecting to NationalMap with https.

Use https for vector tile based region mapping.

---

wwwroot/init/test.json

Include all tests from WPS test server, but also have category for tests that require extra data. This should make it easier to add tests in future.

Update to WPS tests

---

index.js

We haven't needed this since the Knockout days, and removing it reduces the size of nationalmap.js a bit.

Remove unnecessary registration of knockout bindings.

---

LICENSE.md
README.md
ckanext-cesiumpreview/README.md
wwwroot/404.html
wwwroot/500.html
wwwroot/about.html
wwwroot/config.json
wwwroot/help/data-catalogue.html
wwwroot/help/data-workbench.html
wwwroot/help/faq.html
wwwroot/help/help.html
wwwroot/help/map-navigation.html
wwwroot/help/privacy.html
wwwroot/privacy.html

The references to NationalMap are inconsistent.  This PR removes all usages of **The** in front of NationalMap, and replaces "National Map" with NationalMap (no space).  There is also an old link to csv-geo-au I've replaced.

Replace references in HTML pages to "The National Map"

---

package.json

The only change in this version is that `trustProxy` has been set to `"loopback, linklocal, uniquelocal"`, which should help prevent internal network IPs from showing up in feedback issues.

Use 2017-02-23 version of the private server config.

---

index.js

Code in index.js was assuming that all inter-window messages would have an `initSources` property, which is not true when the React Dev Tools send us a message, and in other scenarios.

Don't crash when receiving a message from React Dev Tools.

---

wwwroot/init/test.json

Just to provide a simple example of using `nameInCatalog` (new in the latest TerriaJS), and use it to slightly neaten the #test file.

Use `nameInCatalog` in the test file

---

devserverconfig.json

Add server to proxy list for northernaustralia biogas datasets.
See TerriaJS/NorthernAustralia#79.

Add biogas server to proxy list for northernaustralia

---

lib/Views/Anniversary/Celebration.jsx

* Don't show the popup on app load (but leave the button on the right)
* Change wording to "has turned 5"
* Remove "Don't show again"
Fixes #916

Don't show the celebration popup at start, change wording

---

wwwroot/config.json

A recent config change inadvertently configured National Map to get imagery from Ion instead of Bing. This PR reverts that change.

Get imagery from Bing, not Ion

---

deploy/aws/user-data
package.json

`package_upgrade` is no longer required with SSM and is disabled to prevent a race condition with the nodesource repository update.

Upgrade to NodeJS 14

---

CHANGES.md
gulpfile.js
package.json
yarn.lock

For an unknown reason, the error "EACCES: permission denied" will occur when copying some files from the cache directory to work directory when running the `make-package` gulp task on WSL. It seems that removing this cache directory will not cause errors because that cache is only used in build stage.

2022 09 23 release
