TerriaJS/nationalmap

- wwwroot/init/nm.json
Since this is a change to the main catalogue, we need to clear it with Comms before merging it.  Demo is here:
http://nationalmap.research.nicta.com.au/kring/
New layers are under `Surface Water -> Water Observations from Space`.
> Add Water Observations from Space datasets.

- wwwroot/index.html
This way they work over both http and https.
> Use protocol-agnostic URLs for fonts.

- package.json
- wwwroot/init/nm.json
This depends on TerriaJS/terriajs#682.
> Use HTML GetFeatureInfo for Population Estimates dataset.

- index.less
- wwwroot/config.json
Depends on https://github.com/TerriaJS/terriajs/pull/692 to have
any effect.
[weird, I thought I created this PR  already...]
> Add disclaimer in map. Fixes #11.

- index.js
- package.json
- wwwroot/init/na.json
Set the initial base layer from baseLayerName param in init file.
Share sets the same property in the link to share the users base layer.
There's an example in na.json
Also fixed homeCamera in na.json
> set basemap from init and share link

- CHANGES.md
- index.js
- package.json
Requires TerriaJS/terriajs#706.
> Initially hide explorer panel when #hideExplorerPanel=1

- CHANGES.md
- index.less
- wwwroot/index.html
Fixes #12 
The quality of the result varies greatly among browsers and between the 2D and 3D view, ranging from "pretty good" to "mostly readable".
> Add print disclaimer.

- CHANGES.md
- index.js
- index.less
- package.json
> Use the Now Viewing attention grabber

- lib/Views/RelatedMaps.html
> na map text update

- wwwroot/init/nm.json
This change won't have any effect until TerriaJS/terriajs#attentionGrabber is merged.
> Add attention grabbing to all ABS items.

- wwwroot/init/nm.json
added a link for more about abs data, and also put the links under datacustodian in the absGroup so that it will flow through to the item.
> added more info to group and one more link to items

- wwwroot/config.json
Hi Team,
Just a quick fix for disclaimer link config. Currently 404s and redirects to the app.
Cheers.
> Fix disclaimer link

- wwwroot/init/abs.json
example tableStyle in abs.json
> sample styling on abs in abs.json

- index.js
- package.json
remove localestring from animation controller  (for terriajs #771)
> remove locale to deal with ie9

- datasources/000_settings.json
- wwwroot/config.json
> Replace data.gov.au with s3-ap-southeast-2.amazonaws.com

- CHANGES.md
- datasources/00_National_Data_Sets/00_00_Communications.json
- datasources/00_National_Data_Sets/00_01_Elevation.json
- datasources/00_National_Data_Sets/00_02_Framework.json
- datasources/00_National_Data_Sets/00_03_Ground_Water.json
- datasources/00_National_Data_Sets/00_04_Habitation.json
- datasources/00_National_Data_Sets/00_05_Infrastructure.json
- datasources/00_National_Data_Sets/00_06_Land.json
- datasources/00_National_Data_Sets/00_07_National_Boundaries.json
- datasources/00_National_Data_Sets/00_08_Social_and_Economic.json
- datasources/00_National_Data_Sets/00_09_Statistical_Boundaries.json
- datasources/00_National_Data_Sets/00_10_Surface_Water.json
- datasources/00_National_Data_Sets/00_11_Terrain.json
- datasources/00_National_Data_Sets/00_12_Transport.json
- datasources/00_National_Data_Sets/00_13_Utility.json
- datasources/00_National_Data_Sets/00_14_Vegetation.json
This is much like #73 except it does NOT include the switch to the new GA datasets.
> Catalogue improvements, without switching to the GA datasets.

- CHANGES.md
- datasources/00_National_Data_Sets/00_07_National_Boundaries.json
Commonwealth electoral divisions boundaries from aec
> official aec boundaries

- datasources/08_South_Australian_Government.json
- package.json
* Use terriajs 1.0.34.
* Search only for datasets with their jurisdiction set to "Government of South Australia".
> South Australia CKAN tweaks

- CHANGES.md
- datasources/00_National_Data_Sets/00_00_Communications.json
* Use `mybroadband:` layers instead of `public:` layers.
* Set opacity of black spot datasets to 100%.
> Tweaks for DoC.

- CHANGES.md
- datasources/02_Data_Providers.json
- datasources/04_ACT_Government.json
- wwwroot/init/act.json
See https://github.com/TerriaJS/terriajs/pull/853
> Add City of Melbourne and ACT. (Requires Socrata support).

- CHANGES.md
- index.js
- package.json
- wwwroot/config.json
Add url shortening to nationalmap.  This is almost all in terriajs with adding it here just adding a urlShortener object to start.
- before merging need to remove key from config and change package.json terriajs link
config.json key will be set in deployment.  To test locally, key needs to be added back into config.json
> url shortening

- index.js
Implementing the other half of https://github.com/TerriaJS/terriajs/issues/864
> Pass 'true' to use basemap cookie.

- gulpfile.js
> Remove spammy browserify JSON error dumps.

- CHANGES.md
- datasources/00_National_Data_Sets/00_01_Ground_Water.json
- datasources/00_National_Data_Sets/00_07_Framework.json
- datasources/00_National_Data_Sets/00_08_Habitation.json
- datasources/00_National_Data_Sets/00_09_Infrastructure.json
- datasources/00_National_Data_Sets/00_10_Surface_Water.json
- datasources/00_National_Data_Sets/00_11_Terrain.json
- datasources/00_National_Data_Sets/00_13_Utility.json
- datasources/00_National_Data_Sets/00_14_Vegetation.json
- datasources/00_National_Data_Sets/00_15_Elevation.json
- package.json
Try it here:
http://nationalmap.research.nicta.com.au/demo
> Flatten the National Data Sets

- index.js
- wwwroot/help/data-catalogue.html
- wwwroot/help/howto.html
- Update NM brand
- Add videos to help docs
> Remove beta tag from NM brand

- CHANGES.md
- README.md
- index.js
- wwwroot/about.html
- wwwroot/config.json
- wwwroot/help/data-catalogue.html
- wwwroot/help/faq.html
- wwwroot/help/howto.html
- wwwroot/help/map-navigation.html
- wwwroot/help/now-viewing.html
- wwwroot/help/search-tab.html
- wwwroot/privacy.html
> Update for move to PM&C.

- CHANGES.md
- wwwroot/config.json
> Add IMOS and AODN geoservers to proxy allowed hosts.

- CHANGES.md
- datasources/00_National_Data_Sets/00_12_Transport.json
Under `Transport -> Freight`
Fixes #127
> Add Freight data

- CHANGES.md
- wwwroot/about.html
- wwwroot/help/data-catalogue.html
- wwwroot/help/howto.html
> Use YouTube videos hosted in the AusGovDPMC account.

- index.js
- package.json
Upgrades TerriaJS to 1.0.49, and enables TerriaJS/terriajs#1136 for NationalMap.
> Upgrade TerriaJS and enable postMessage feature

- wwwroot/help/howto.html
> Make "How to" information clearer about spreadsheets.

- datasources/00_National_Data_Sets/00_16_Environment.json
> Add environment.gov.au web services to catalog

- wwwroot/data/regionMapping.json
I think this might have been missed by accident.
> Add sa4_code_2011 as an alias for sa4

- datasources/00_National_Data_Sets/00_00_Communications.json
- datasources/00_National_Data_Sets/00_01_Ground_Water.json
- datasources/00_National_Data_Sets/00_02_Land.json
- datasources/00_National_Data_Sets/00_03_National_Boundaries.json
- datasources/00_National_Data_Sets/00_04_Social_and_Economic.json
- datasources/00_National_Data_Sets/00_05_Statistical_Boundaries.json
- datasources/00_National_Data_Sets/00_10_Surface_Water.json
- datasources/00_National_Data_Sets/00_15_Elevation.json
- datasources/03_Australian_Bureau_of_Statistics_(BETA).json
- datasources/09_Tasmanian_Government.json
(See comments at https://github.com/TerriaJS/terriajs/pull/1236 )
> Use numbers, not numeric strings ("1.0") in init files.

- CHANGES.md
- datasources/00_National_Data_Sets/00_00_Communications.json
- datasources/00_National_Data_Sets/00_02_Land.json
- datasources/00_National_Data_Sets/00_04_Social_and_Economic.json
Merge after TerriaJS/terriajs#1292 is merged.
> Use CkanCatalogItem

- datasources/00_National_Data_Sets/00_05_Statistical_Boundaries.json
- wwwroot/init/test.json
> Provide direct downloads for statistical boundaries from ABS.

- wwwroot/data/regionMapping.json
> Handle 3-digit postcodes caused by upstream data mishandling.

- CHANGES.md
- datasources/11_Western_Australian_Government.json
- gulpfile.js
It works well, although a bit slow to load initially.
> Add WA data using their new (beta) CKAN catalogue.

- wwwroot/config.json
See this issue for details: 
https://github.com/TerriaJS/terriajs/issues/1591#issuecomment-225079098
> adding print disclaimer

- CHANGES.md
- index.js
- lib/Styles/NationalMap.less
- lib/ViewModels/PreviewLinkViewModel.js
- lib/Views/PreviewLink.html
> Add a prominent link to the preview of the new UI

- CHANGES.md
- wwwroot/data/regionMapping.json
> add cnt3 as alias for iso3

- wwwroot/about.html
- wwwroot/public/css/custom.css
Make the logos appear behind main column on mobile
> move column ordering on mobile

- buildprocess/webpack.config.js
- devserverconfig.json
- index.js
This should fix the Travis build.
> Fix incorrect case in require'd name.

- lib/Views/global.scss
> feature td padding

- wwwroot/init/test.json
Note line test isn't going to work until https://github.com/TerriaJS/terriajs/pull/2031 is in.
> Add WPS functions in test data for easy testing

- wwwroot/init/test.json
Fixes TerriaJS/terriajs#2167
Before merging:
> Stop TerriaJS treating auto incidents csv as animated

- CHANGES.md
- lib/Views/UserInterface.jsx
> Add Measure Tool

- index.js
This requires https://github.com/TerriaJS/terriajs/pull/2316.
Fixes TerriaJS/terriajs#2302.
Fixes #398
> Filter out old catalogs from start data.

- CHANGES.md
- lib/Views/RelatedMaps.jsx
Addresses the NationalMap version of this problem: https://github.com/TerriaJS/neii-viewer/issues/85
> Fix link to NEII viewer from image

- package.json
Closes #440
https://greenkeeper.io/
> chore(package): update terriajs to version 4.10.3

- wwwroot/404.html
- wwwroot/500.html
- wwwroot/about.html
- wwwroot/help/data-catalogue.html
- wwwroot/help/data-workbench.html
- wwwroot/help/faq.html
- wwwroot/help/help.html
- wwwroot/help/map-navigation.html
- wwwroot/help/privacy.html
- wwwroot/privacy.html
@tobybellwood can you merge this if you're happy with it?
CC @bsimyo
> NICTA -> CSIRO, mention basemap / dataset usage rights.

- CHANGES.md
- devserverconfig.json
> Add adelaidemetro.com.au to proxy whitelist.

- wwwroot/data/regionMapping.json
I copied the `regionMapping.json` from TerriaMap, so this also adds `analyticsWmsLayerName` and `analyticsWmsServer` to all the region types.
> Add aus_code_2011 and aus_code_2016 as aliases for AUS region type.

- devserverconfig.json
> Add data61.io and d61.io to the proxy whitelist.

- CHANGES.md
- wwwroot/404.html
- wwwroot/500.html
- wwwroot/about.html
- wwwroot/help/faq.html
- wwwroot/help/help.html
https://github.com/TerriaJS/nationalmap/pull/614 changed it in the app but still getting forwarded issues due to the static content pages
> Changed the support email address to DTA

- devserverconfig.json
> Add tern.org.au to the proxy whitelist

- wwwroot/help/help.html
> Fixed indentation in help.html

- wwwroot/help/data-catalogue.html
Fixes https://github.com/TerriaJS/nationalmap/issues/708 (https://github.com/TerriaJS/terriajs/issues/2844)
> Update Data Catalogue - add multiple layers

- wwwroot/help/help.html
Corrected entirely and polygon in this PR https://github.com/TerriaJS/nationalmap/pull/706
> Correcting typos

- wwwroot/help/css/custom.css
- wwwroot/help/help.html
- wwwroot/help/js/scrollIt.js
Fix https://github.com/TerriaJS/terriajs/issues/2877
> Nice navigation for help page, expose header

- CHANGES.md
> Add geojson for the layer to work

- CHANGES.md
- package.json
- yarn.lock
1. Not tagged yet.
2. Updated to terriajs version `7.11.3` published in npm.
> 2020-03-20 release candidate

- CHANGES.md
- lib/Views/Anniversary/Celebration.jsx
- lib/Views/Anniversary/celebration.scss
- lib/Views/UserInterface.jsx
Resolves https://github.com/TerriaJS/nationalmap/issues/971
> Update celebration modal to have v8 text instead

- CHANGES.md
- lib/Views/Anniversary/Celebration.jsx
- lib/Views/Anniversary/celebration.scss
Added message for AREMI users to check National Map beta for ported datasets.
> Add message for AREMI users

- devserverconfig.json
Fix missing `"` in devserverconfig.json.
> Fix syntax error in devserverconfig.json.

- lib/Views/UserInterface.jsx
- package-lock.json
- package.json
- wwwroot/about.html
- wwwroot/help/privacy.html
Address #1053, #1061
- Use terriajs version 8.1.0
- Set package version to 1.0.0
> update about and logos and privacy

- devserverconfig.json
Address #1131 
Also add a new proxy entry due to this issue https://github.com/TerriaJS/nationalmap/issues/1115.
> Do not proxy terria-catalogs-public.storage.googleapis.com.
